DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

MxOline/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.views.static import serve
from MxOline import settings
from apps.operations.views import IndexView
from apps.organizations.views import OrgView
from apps.users.views import LoginView, LogoutView, SendSms, DynamicLoginPostView, RegisterView
import xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # TemplateView是class
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('captcha/', include('captcha.urls')),
    # 不做csrf验证, 这里用了ajax
    path('send_sms/', csrf_exempt(SendSms.as_view()), name='send_sms'),
    # 发送动态手机登录提交
    path('d_login/', DynamicLoginPostView.as_view(), name='d_login'),
    # 上传资源
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 生产要写， 开发环境不要写
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    # 机构
    re_path('^org/', include(('apps.organizations.urls', 'organizations'), namespace='org')),
    # 课程
    re_path('^course/', include(('apps.courses.urls', 'courses'), namespace='course')),

    # 用户操作
    re_path('^op/', include(('apps.operations.urls', 'operations'), namespace='op')),

    # 个人中心
    re_path('^users/', include(('apps.users.urls', 'users'), namespace='users')),
    # 富文本
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

apps/courses/urls.py
#!/bin/python3
# -*- coding: utf-8 -*-
from django.urls import re_path

from apps.courses.views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentView, CourseVideoView

urlpatterns = [
    re_path('^list/$', CourseListView.as_view(), name='list'),
    re_path(r'^(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='detail'),
    re_path(r'^(?P<course_id>\d+)/lesson/$', CourseLessonView.as_view(), name='lesson'),
    re_path(r'^(?P<course_id>\d+)/comments/$', CourseCommentView.as_view(), name='comments'),
    re_path(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)/$', CourseVideoView.as_view(), name='video'),
]

apps/operations/urls.py
#!/bin/python3
# -*- coding: utf-8 -*-
from django.urls import re_path, path

from apps.operations.views import AddFavView, CommentView

urlpatterns = [
    re_path('^fav/$', AddFavView.as_view(), name='fav'),
    re_path('^comment/$', CommentView.as_view(), name='comment'),

]

apps/organizations/urls.py
#!/bin/python3
# -*- coding: utf-8 -*-
from django.urls import re_path

from apps.organizations.views import OrgView, AddAskView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, \
    TeacherView, TeacherDetailView

urlpatterns = [
    re_path('^list/$', OrgView.as_view(), name='list'),

    re_path('^add_ask/$', AddAskView.as_view(), name='add_ask'),
    re_path('^(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='home'),
    re_path('^(?P<org_id>\d+)/teacher/$', OrgTeacherView.as_view(), name='teacher'),
    re_path('^(?P<org_id>\d+)/course/$', OrgCourseView.as_view(), name='course'),
    re_path('^(?P<org_id>\d+)/desc/$', OrgDescView.as_view(), name='desc'),


    # 老师
    re_path('^teachers/$', TeacherView.as_view(), name='teachers'),
    re_path('^teachers/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
#!/bin/python3
# -*- coding: utf-8 -*-
from django.urls import re_path

from apps.users.views import UserInfo, UploadImageView, UpdatePwdView, UpdateMobileView, MyCourseView, MyFavOrgView, \
    MyFavTeacherView, MyFavCourseView, MyMessageView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
urlpatterns = [
    # 个人信息
    re_path('^info/$', UserInfo.as_view(), name='info'),
    re_path('^image/upload/$', UploadImageView.as_view(), name='image'),
    re_path('^image/upload/$', UploadImageView.as_view(), name='image'),
    re_path(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),
    re_path(
        r'^update/mobile/$',
        UpdateMobileView.as_view(),
        name="update_mobile"),
    re_path(r'^mycourse$', login_required(TemplateView.as_view(
        template_name='usercenter-mycourse.html'), login_url='/login/'), {'current_page': '我的课程'}, name="mycourse"),

    re_path(r'^myfavorg/$', MyFavOrgView.as_view(), name="myfavorg"),
    re_path(r'^myfav_teacher/$', MyFavTeacherView.as_view(), name="myfav_teacher"),
    re_path(r'^myfav_course/$', MyFavCourseView.as_view(), name="myfav_course"),
    re_path(r'^my_messages/$', MyMessageView.as_view(), name="my_messages"),
]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href={% static "css/reset.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "css/animate.css" %}>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css" %}>
    <script src={% static "js/jquery.min.js" %} type="text/javascript"></script>
    <script src={% static "js/jquery-migrate-1.2.1.min.js" %} type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->
                   {% if user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{% if user.nick_name %}{{ user.nick_name  }}{% else %}{{ user.username }}{% endif %} <img
                                        class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20"
                                         src="{{ user.image.url }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ user.image.url }}"/></dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                    <a href="{% url 'users:my_messages' %}">
                        <div class="msg-num"><span id="MsgNum">{{ unread }}</span></div>
                    </a>
                </div>

            </div>
            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src={% static  "images/logo.jpg" %}/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="{% if s_type %}{{ s_type }}{% else %}course{% endif %}">
                                {% if s_type == 'course' %}公开课{% endif %}
                                {% if s_type == 'org' %}课程机构{% endif %}
                                {% if s_type == 'teacher' %}授课老师{% endif %}
                                {% if not s_type %}公开课{% endif %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="{{ keywords|default_if_none:'' }}" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src={% static "images/search_btn.png" %}/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li class="{% if  request.path == '/' %}active{% endif %} "><a href="{% url 'index' %}">首页</a></li>
                            <li class="{% if  request.path|slice:'7' == '/course' %}active{% endif %} "><a href="{% url 'course:list' %}">公开课<img class="hot" src={% static "images/nav_hot.png" %}></a></li>
                            <li class="{% if  request.path|slice:'13' == '/org/teachers' %}active{% endif %} "><a href="{% url 'org:teachers' %}">授课教师</a></li>
							<li class="{% if request.path|slice:'13' != '/org/teachers' %}{% if request.path|slice:'4' == '/org' %}active{% endif %}{% endif %}" ><a href="{% url 'org:list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->





{% block custom_bread %}
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src={% static  "images/footlogo.png" %}/></a></li>
                <li class="code"><img src={% static  "images/code.jpg" %}/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src={% static "images/tell.png" %}/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src={% static  "js/selectUi.js" %} type='text/javascript'></script>
<script src={% static  "js/deco-common.js" %} type='text/javascript'></script>
<script type="text/javascript" src={% static  "js/plugins/laydate/laydate.js" %}></script>
<script src={% static  "js/plugins/layer/layer.js" %}></script>
<script src={% static "js/plugins/queryCity/js/public.js" %} type="text/javascript"></script>
<script src={% static "js/unslider.js" %} type="text/javascript"></script>
<script src={% static "js/plugins/jquery.scrollLoading.js" %} type="text/javascript"></script>
<script src={% static  "js/deco-common.js" %} type="text/javascript"></script>
{% block custom_js %}
{% endblock %}
{% block custom_css %}
{% endblock %}

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load static %}
{% block title %}
    我的课程- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
        <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li {% if current_page == 'my_fav_org' %}class="active"{% endif %}><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li {% if current_page == 'my_fav_teacher' %}class="active"{% endif %}><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li {% if current_page == 'my_fav_course' %}class="active"{% endif %}><a href="{% url 'users:myfav_course' %}">公开课程 </a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in all_courses %}
                            <div class="module1_5 box">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="190" src="{{ course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}


{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav'%}",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load static %}
{% block title %}
    收藏機構- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>收藏機構</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li {% if current_page == 'my_fav_org' %}class="active"{% endif %}><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li {% if current_page == 'my_fav_teacher' %}class="active"{% endif %}><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li {% if current_page == 'my_fav_course' %}class="active"{% endif %}><a href="{% url 'users:myfav_course' %}">公开课程 </a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in all_orgs %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:home' org.id %}">
                                    <img width="160" height="90" src="{{ org.image.url }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                {% if org.is_auth %}
                                    <img src="{% static 'images/authentication.png' %}"/>
                                {% endif %}
                                {% if org.is_gold %}
                                    <img src="{% static 'images/gold.png' %}"/>
                                {% endif %}
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav'%}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}
{% load static %}
{% block title %}
    我的消息- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="{% url 'users:my_messages' %}">个人消息</a> </li>
				</ul>


			</div>
			<div class="messagelist">
                    {% for message in messages.object_list %}
                        <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
			</div>


			<div class="pageturn pagerright">
                <ul class="pagelist">
                {% if messages.has_previous %}
                    <li class="long"><a href="?{{ messages.previous_page_number.querystring }}">上一页</a></li>
                {% endif %}

                {% for page in messages.pages %}
                    {% if page %}
                        {% ifequal page messages.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none">...</li>
                    {% endif %}
                {% endfor %}
                {% if messages.has_next %}
                    <li class="long"><a href="?{{ messages.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
            </ul>
            </div>
		</div>

	</div>
{% endblock %}